name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps

      - name: Create folders
        run: |
          mkdir -p Reports
          mkdir -p auth

      - name: Generate auth state for ${{ matrix.browser }}
        run: |
          pytest tests/test_auth_setup.py -v --env=qa --browser ${{ matrix.browser }}

      - name: Run tests on ${{ matrix.browser }}
        run: |
          pytest tests/test_login.py tests/test_login_data.py tests/test_inventory.py tests/test_cart.py tests/test_checkout.py tests/test_file_upload.py tests/test_file_download.py tests/test_dialogs.py tests/test_multiple_tabs.py tests/test_iframe.py tests/test_network_interception.py -v --env=qa --browser ${{ matrix.browser }} --html=Reports/pwreport-${{ matrix.browser }}.html --self-contained-html --tracing=retain-on-failure --screenshot=only-on-failure --alluredir=allure-results-${{ matrix.browser }}

      - name: Upload HTML report for ${{ matrix.browser }}
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-test-report-${{ matrix.browser }}
          path: Reports/pwreport-${{ matrix.browser }}.html

      - name: Upload Playwright test results for ${{ matrix.browser }}
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results-${{ matrix.browser }}
          path: test-results/

      - name: Upload Allure results for ${{ matrix.browser }}
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}
          path: allure-results-${{ matrix.browser }}/